# Generated by Django 5.0.6 on 2024-06-10 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_category_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='product',
            name='updated_at',
        ),
    ]
